server:
  port: 8090
dubbo:
  scan:
    base-packages: com.wise.dubbo.provider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://192.168.163.21:8848
spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.163.21:8848
  main:
    allow-bean-definition-overriding: true